# Generated by Django 2.0.1 on 2018-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_done',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_done',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='project',
            name='in_work',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='workday',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
