# Generated by Django 2.0.1 on 2018-02-04 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180204_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default='False')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.Project')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='project',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
