# Generated by Django 2.0.2 on 2018-02-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180204_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
    ]
