# Generated by Django 2.0.1 on 2018-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180205_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='elapsed_time',
            field=models.DurationField(default=0),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
