# Generated by Django 2.0.1 on 2018-02-06 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180206_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='workday',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
