# Generated by Django 2.0.1 on 2018-02-06 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180206_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='id',
        ),
        migrations.AlterField(
            model_name='workday',
            name='date',
            field=models.DateField(default=datetime.date.today, primary_key=True, serialize=False),
        ),
    ]
