# Generated by Django 2.0.1 on 2018-02-06 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180206_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-datetime',)},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datetime',
        ),
    ]
