# Generated by Django 2.0.1 on 2018-02-08 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20180206_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('end_date',)},
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
